---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: food-app-common
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: food-app
  validation: client

