---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: food-app
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: food-app
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcd-bot
    messageTemplate: '[ci skip] update image'
  interval: 1m0s
  update:
    setters: {}

