---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: frontend-food-app
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: frontend
    namespace: food-app
  interval: 10m0s
  path: ./k8s/frontend
  prune: true
  sourceRef:
    kind: GitRepository
    name: food-app
  timeout: 2m0s
  validation: client

